### ISSUE TITLE
[BUG] Moving splat into a cube stops SpatialGizmo

### ISSUE THREAD

**Issue by nonunknown** [ExpiredPopsicle/KiriSplat#1]
Using Godot 3.2 mono at ubuntu 19.10

As you can see:
![splat](https://user-images.githubusercontent.com/58845030/77342902-a8135e00-6d0f-11ea-9ba6-d45ed4dc0bad.gif)

when a move the splat, the spatial gizmo does not update!

**Comment by ExpiredPopsicle** [comment]
Fixed in 3d80f7eac1e6d5aef21da33f8a746a3d0f096b33 .

**Comment by ExpiredPopsicle** [comment]
Nevermind. I need to take another look into this.

**Comment by ExpiredPopsicle** [comment]
This might just be a product of Godot recalculating the bounds constantly in reaction to the plugin constantly changing the geometry as it moves.

**Comment by ExpiredPopsicle** [comment]
I figured out a fix that doesn't hurt performance. I'll get it in soon.

**Comment by ExpiredPopsicle** [comment]
Fixed in e931edcc7ffaf846a5765698827282c052d405da . (For real this time... Probably.)
